dependencies:
- alias: expose
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- alias: cleanup
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- name: bdd-test-spring-boot-http-gradle-1531177301
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: bdd-test-rust-http-1531177301
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: bdd-test-vertx-rest-prometheus-1531177301
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: bdd-test-spring-boot-web-1531177301
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.0
- name: bdd-test-import-1531177301
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.0
